name: Deploy Hexo
on: [push]
jobs:
  deploy:
    name: Deploy Hexo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: v14.x

      - name: Install and Build
        run: npm i && npx hexo clean && npx hexo deploy -g

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: public
